### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by ousamabenyounes** [meddeb9989/tntbankapp#1]
tntbankapp/bankserver/serverapp/sendemail_valid.py has been compromised and your login/pwd are now visible on this project
to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects...

Hope this will help you :)

**Comment by meddeb9989** [comment]
Hello ousama, 
Thank you for your security issue, in fact this was a project for my studies, however these login/pwd are not really interesting but i'll change them anyway.

Have a nice day
